language: go

matrix:
  include:
    - go: 1.13.x
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.11.x
      env: GO111MODULE=on

install:
  - go get -u
script:
  - go test ./...
  - go build ./cmd/kubeprober