port: 8081

tests:
  - name: check-oom
    description: Check Log for OutOfMemoryError
    regex:
      - "OutOfMemoryError"
  - name: check-health-endpoint
    description: Check Health Endpoint
    httpGet:
      httpHeaders:
        - name: Host
          value: test.de
      path: /info
      port: 8080
      scheme: HTTP
      sync: false

readinessProbes:
  - name: Check for out-of-memory
    container: main
    performTests:
      - check-oom
    successThreshold: 1
    failureThreshold: 3
    periodSeconds: 10

livenessProbes:
  - name: Check for out-of-memory
    container: main
    performTests:
      - check-oom
    successThreshold: 1
    failureThreshold: 3
    periodSeconds: 20