apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeprober-test
  labels:
    app: kubeprober
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubeprober
  template:
    metadata:
      labels:
        app: kubeprober
  spec:
    serviceAccount: kubeprober
    containers:
      - name: main
        image: openshift/origin-cli:v3.11
        imagePullPolicy: IfNotPresent
      - name: kubeprober
        image: lukeelten/kubeprober
        imagePullPolicy: Always
        volumeMounts:
          - name: kubeprober-config
            mountPath: /app
            readOnly: true
    volumes:
      - name: config
        configMap:
          name: kubeprober-config